alpha-dog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

alpha-dog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alpha-dog/app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum:6, maximum:100}
    validates :description, presence: true, length: {minimum:10, maximum:300}
end

alpha-dog/app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    has_many :articles
    validates :username, presence: true, 
                uniqueness: {case_sensitive: false}, length: {minimum:3, maximum:25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                uniqueness: {case_sensitive: false}, length: {maximum:105},
                format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end

alpha-dog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

alpha-dog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end

    def index
        @articles = Article.all
    end

    def new 
        @article = Article.new
    end

    def edit 
    end

    def create 
        @article = Article.new(article_param)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to @article 
        else 
            render 'new'
        end
    end

    def update 
        if @article.update(article_param)
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy 
        @article.destroy
        redirect_to articles_path
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end

    def article_param 
        params.require(:article).permit(:title, :description)
    end

end

alpha-dog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

alpha-dog/app/helpers/application_helper.rb
module ApplicationHelper
end

alpha-dog/app/helpers/pages_helper.rb
module PagesHelper
end

alpha-dog/app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>The following errors prevented the article from being saved</h2>
    <ul>
        <% @article.errors.full_messages.each do |error| %>
            <li><%= error%></li>
        <% end %>
    </ul>
<% end %>

<p><strong>Author: </strong><%= @article.user.username%></p>

<%= form_with(model: @article, local: true) do |f|%>
    <p>
        <%= f.label :title %>
        <br/>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %>
        <br/>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

alpha-dog/app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render 'form' %>
<%= link_to 'Cancel and return to articles list', articles_path%>

alpha-dog/app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<p>
    <%= link_to 'Create new article', new_article_path%>
</p>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Author</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <td><%= article.user.username%></td>
                <td><%= link_to 'Show', article_path(article) %></td>
                <td><%= link_to 'Edit', edit_article_path(article) %></td>
                <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }%></td>
            </tr>
        <% end %>
    </tbody>
</table>

alpha-dog/app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles list', articles_path%>

alpha-dog/app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>Author: </strong><%= @article.user.username %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to articles list', articles_path%>

alpha-dog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaDog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <%= message%>
    <% end %>
    <%= yield %>
  </body>
</html>

alpha-dog/app/views/pages/about.html.erb
<h1>This is an assignment for udemy course</h1>
<%= link_to 'Articles list', articles_path%> | 
<%= link_to 'Home', root_path%>

alpha-dog/app/views/pages/home.html.erb
<h1>Welcome to Alpha Blog</h1>

<%= link_to 'Articles list', articles_path%> | 
<%= link_to 'About', about_path%>